In [1]:
import pandas as pd
import numpy as np
import requests
import tweepy
import json
import sqlalchemy

 IMPORTAR OS DADOS

In [2]:
twitter_arc = pd.read_csv('twitter-archive-enhanced.csv')
twitter_arc.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None

In [ ]:
response = requests.get('https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv')
with open('image_predictions.tsv',mode='wb') as file:
    file.write(response.content)

In [2]:
ls

esta/                  tweet_json.txt                Untitled.ipynb
ID_error.txt           twitter-archive-enhanced.csv
image_predictions.tsv  Untitled1.ipynb

In [3]:
imagens_pre = pd.read_csv('image_predictions.tsv',sep='\t')
imagens_pre.head()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

In [ ]:
consumer_key = 'jlbF6JYyw3GZQFy7XkOdwGZTP'
consumer_secret = 'xj7URa3ieoL2U0uroNKEnZnCLe9CGMNw6xSEhPlZq989O0cYx0'
access_token = '1036776919323303937-cxZxM2aG0MwutEuKEGRoMtPMYI60tU'
access_secret = 'hi2BZDEWK94LXll9ZbjbutV7Pi04HpzXiEsjjc47CzNsG'
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)

api = tweepy.API(auth,parser=tweepy.parsers.JSONParser())

Tweet = []
Erro = []
for i in df['tweet_id']:
    try:
        Tweet.append(api.get_status(i,tweet_mode='extended'))
    except:
        Erro.append(i)

In [ ]:
with open ('tweet_json.txt','w') as outfile:
    for i in Tweet:
        json.dump(i, outfile)
        outfile.write('\n')
        
with open ('ID_error.txt','w') as outfile:
    for i in Erro:
        outfile.write(str(i))
        outfile.write('\n')

In [4]:
Matrix_json = []
with open('tweet_json.txt') as f:
    for line in f:
        Matrix_json.append(json.loads(line))

In [5]:
tweet_js= pd.DataFrame(Matrix_json)
tweet_js.head()

,contributors,coordinates,created_at,display_text_range,entities,extended_entities,favorite_count,favorited,full_text,geo,...,lang,place,possibly_sensitive,possibly_sensitive_appealable,retweet_count,retweeted,retweeted_status,source,truncated,user
0,None,None,Sun Nov 15 22:32:08 +0000 2015,"[0, 131]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666020881337073664, 'id_str'...",2551,False,Here we have a Japanese Irish Setter. Lost eye...,None,...,en,None,False,False,508,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1,None,None,Sun Nov 15 23:05:30 +0000 2015,"[0, 139]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666029276303482880, 'id_str'...",128,False,This is a western brown Mitsubishi terrier. Up...,None,...,en,None,False,False,47,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
2,None,None,Sun Nov 15 23:21:54 +0000 2015,"[0, 130]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666033409081393153, 'id_str'...",125,False,Here is a very happy pup. Big fan of well-main...,None,...,en,None,False,False,44,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
3,None,None,Mon Nov 16 00:04:52 +0000 2015,"[0, 137]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666044217047650304, 'id_str'...",296,False,This is a purebred Piers Morgan. Loves to Netf...,None,...,en,None,False,False,139,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
4,None,None,Mon Nov 16 00:24:50 +0000 2015,"[0, 120]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666049244999131136, 'id_str'...",108,False,Here we have a 1949 1st generation vulpix. Enj...,None,...,en,None,False,False,40,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."

OLHANDO OS DADOS

TWEET_ARC

In [10]:
tweet_js

,contributors,coordinates,created_at,display_text_range,entities,extended_entities,favorite_count,favorited,full_text,geo,...,lang,place,possibly_sensitive,possibly_sensitive_appealable,retweet_count,retweeted,retweeted_status,source,truncated,user
0,None,None,Sun Nov 15 22:32:08 +0000 2015,"[0, 131]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666020881337073664, 'id_str'...",2551,False,Here we have a Japanese Irish Setter. Lost eye...,None,...,en,None,False,False,508,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1,None,None,Sun Nov 15 23:05:30 +0000 2015,"[0, 139]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666029276303482880, 'id_str'...",128,False,This is a western brown Mitsubishi terrier. Up...,None,...,en,None,False,False,47,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
2,None,None,Sun Nov 15 23:21:54 +0000 2015,"[0, 130]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666033409081393153, 'id_str'...",125,False,Here is a very happy pup. Big fan of well-main...,None,...,en,None,False,False,44,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
3,None,None,Mon Nov 16 00:04:52 +0000 2015,"[0, 137]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666044217047650304, 'id_str'...",296,False,This is a purebred Piers Morgan. Loves to Netf...,None,...,en,None,False,False,139,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
4,None,None,Mon Nov 16 00:24:50 +0000 2015,"[0, 120]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666049244999131136, 'id_str'...",108,False,Here we have a 1949 1st generation vulpix. Enj...,None,...,en,None,False,False,40,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
5,None,None,Mon Nov 16 00:30:50 +0000 2015,"[0, 140]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666050754986266625, 'id_str'...",132,False,This is a truly beautiful English Wilson Staff...,None,...,en,None,False,False,59,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
6,None,None,Mon Nov 16 00:35:11 +0000 2015,"[0, 138]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666051848592334848, 'id_str'...",1210,False,This is an odd dog. Hard on the outside but lo...,None,...,en,None,False,False,843,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
7,None,None,Mon Nov 16 00:49:46 +0000 2015,"[0, 140]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666055517517848576, 'id_str'...",433,False,Here is a Siberian heavily armored polar bear ...,None,...,en,None,False,False,246,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
8,None,None,Mon Nov 16 00:55:59 +0000 2015,"[0, 124]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666057085227016192, 'id_str'...",294,False,My oh my. This is a rare blond Canadian terrie...,None,...,en,None,False,False,141,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
9,None,None,Mon Nov 16 01:01:59 +0000 2015,"[0, 135]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666058597072306176, 'id_str'...",111,False,Here is the Rand Paul of retrievers folks! He'...,None,...,en,None,False,False,57,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
10,None,None,Mon Nov 16 01:22:45 +0000 2015,"[0, 107]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666063820255862784, 'id_str'...",471,False,This is the happiest dog you will ever see. Ve...,None,...,en,None,False,False,216,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
11,None,None,Mon Nov 16 01:52:02 +0000 2015,"[0, 137]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666071190449033216, 'id_str'...",145,False,Here we have a northern speckled Rhododendron....,None,...,en,None,False,False,59,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
12,None,None,Mon Nov 16 01:59:36 +0000 2015,"[0, 137]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666073098362486784, 'id_str'...",319,False,Let's hope this flight isn't Malaysian (lol). ...,None,...,en,None,False,False,163,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
13,None,None,Mon Nov 16 02:38:37 +0000 2015,"[0, 125]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666082912819875840, 'id_str'...",116,False,Here we have a well-established sunblockerspan...,None,...,en,None,False,False,44,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
14,None,None,Mon Nov 16 03:22:39 +0000 2015,"[0, 132]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666093996847063040, 'id_str'...",163,False,This appears to be a Mongolian Presbyterian mi...,None,...,en,None,False,False,73,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
15,None,None,Mon Nov 16 03:44:34 +0000 2015,"[0, 140]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666099505364733952, 'id_str'...",153,False,Can stand on stump for what seems like a while...,None,...,en,None,False,False,67,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
16,None,None,Mon Nov 16 03:55:04 +0000 2015,"[0, 128]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666102150364286977, 'id_str'...",80,False,Oh my. Here you are seeing an Adobe Setter giv...,None,...,en,None,False,False,12,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
17,None,None,Mon Nov 16 04:02:55 +0000 2015,"[0, 134]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666104129232740352, 'id_str'...",14207,False,Not familiar with this breed. No tail (weird)....,None,...,en,None,False,False,6515,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
18,None,None,Mon Nov 16 14:57:41 +0000 2015,"[0, 82]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666268904428277760, 'id_str'...",102,False,Very concerned about fellow dog trapped in com...,None,...,en,None,False,False,35,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
19,None,None,Mon Nov 16 15:14:19 +0000 2015,"[0, 46]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666273081518768128, 'id_str'...",174,False,Can take selfies 11/10 https://t.co/ws2AMaNwPW,None,...,en,None,False,False,76,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
20,None,None,Mon Nov 16 16:11:11 +0000 2015,"[0, 136]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666287399580733440, 'id_str'...",146,False,This is an Albanian 3 1/2 legged Episcopalian...,None,...,en,None,False,False,64,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
21,None,None,Mon Nov 16 16:37:02 +0000 2015,"[0, 138]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666293909010702337, 'id_str'...",497,False,This is a funny dog. Weird toes. Won't come do...,None,...,en,None,False,False,352,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
22,None,None,Mon Nov 16 19:31:45 +0000 2015,"[0, 139]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666337857791987715, 'id_str'...",197,False,This is an extremely rare horned Parthenon. No...,None,...,en,None,False,False,90,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
23,None,None,Mon Nov 16 20:01:42 +0000 2015,"[0, 112]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666345414279471104, 'id_str'...",292,False,Look at this jokester thinking seat belt laws ...,None,...,en,None,False,False,134,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
24,None,None,Mon Nov 16 20:32:58 +0000 2015,"[0, 135]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666353280906170368, 'id_str'...",219,False,Here we have a mixed Asiago from the Galápagos...,None,...,en,None,False,False,71,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
25,None,None,Mon Nov 16 21:10:36 +0000 2015,"[0, 140]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666362717482020864, 'id_str'...",773,False,Unique dog here. Very small. Lives in containe...,None,...,en,None,False,False,566,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
26,None,None,Mon Nov 16 21:54:18 +0000 2015,"[0, 81]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666373746337402880, 'id_str'...",186,False,Those are sunglasses and a jean jacket. 11/10 ...,None,...,en,None,False,False,92,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
27,None,None,Mon Nov 16 23:23:41 +0000 2015,"[0, 137]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666396240351993856, 'id_str'...",167,False,Oh goodness. A super rare northeast Qdoba kang...,None,...,en,None,False,False,84,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
28,None,None,Tue Nov 17 00:06:54 +0000 2015,"[0, 139]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666407121513275392, 'id_str'...",108,False,This is a southern Vesuvius bumblegruff. Can d...,None,...,en,None,False,False,40,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
29,None,None,Tue Nov 17 00:24:19 +0000 2015,"[0, 140]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666411498068123649, 'id_str'...",440,False,This is quite the dog. Gets really excited whe...,None,...,en,None,False,False,324,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1165,None,None,Sat Jul 15 16:17:19 +0000 2017,"[0, 94]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 886258377298292737, 'id_str'...",27674,False,This is Waffles. His doggles are pupside down....,None,...,en,None,False,False,6209,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1166,None,None,Sat Jul 15 23:25:31 +0000 2017,"[0, 131]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 886366138128449536, 'id_str'...",20953,False,This is Roscoe. Another pupper fallen victim t...,None,...,en,None,False,False,3163,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1167,None,None,Sun Jul 16 20:14:00 +0000 2017,"[0, 71]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 886680331239161856, 'id_str'...",22167,False,This is Derek. He's late for a dog meeting. 13...,None,...,en,None,False,False,4413,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1168,None,None,Sun Jul 16 23:58:41 +0000 2017,"[0, 121]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 886736868116754432, 'id_str'...",11910,False,This is Mingus. He's a wonderful father to his...,None,...,en,None,False,False,3250,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1169,None,None,Mon Jul 17 16:17:36 +0000 2017,"[0, 101]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 886983218871902208, 'id_str'...",34756,False,This is Maya. She's very shy. Rarely leaves he...,None,...,en,None,False,False,7691,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1170,None,None,Tue Jul 18 00:07:08 +0000 2017,"[0, 129]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 887101385971384320, 'id_str'...",30207,False,This... is a Jubilant Antarctic House Bear. We...,None,...,en,None,False,False,5894,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1171,None,None,Tue Jul 18 16:08:03 +0000 2017,"[0, 88]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 887343120832229379, 'id_str'...",33297,False,You may not have known you needed to see this ...,None,...,en,None,False,False,10288,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1172,None,None,Wed Jul 19 00:47:34 +0000 2017,"[0, 99]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 887473949361045505, 'id_str'...",68301,False,This is Canela. She attempted some fancy porch...,None,...,en,None,False,False,17985,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1173,None,None,Wed Jul 19 03:39:09 +0000 2017,"[0, 108]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 887517108413886465, 'id_str'...",45738,False,I've yet to rate a Venezuelan Hover Wiener. Th...,None,...,en,None,False,False,11531,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1174,None,None,Wed Jul 19 16:06:48 +0000 2017,"[0, 127]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 887705281597243393, 'id_str'...",29822,False,This is Jeffrey. He has a monopoly on the pool...,None,...,en,None,False,False,5325,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1175,None,None,Thu Jul 20 16:49:33 +0000 2017,"[0, 127]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 888078426338406400, 'id_str'...",21517,False,This is Gerald. He was just told he didn't get...,None,...,en,None,False,False,3454,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1176,None,None,Sat Jul 22 00:23:06 +0000 2017,"[0, 87]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 888554915546542081, 'id_str'...",19654,False,This is Ralphus. He's powering up. Attempting ...,None,...,en,None,False,False,3531,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1177,None,None,Sat Jul 22 16:56:37 +0000 2017,"[0, 128]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 888804981515575296, 'id_str'...",25296,False,This is Zeke. He has a new stick. Very proud o...,None,...,en,None,False,False,4272,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1178,None,None,Sun Jul 23 00:22:39 +0000 2017,"[0, 86]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 888917229776945152, 'id_str'...",28761,False,This is Jim. He found a fren. Taught him how t...,None,...,en,None,False,False,4448,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1179,None,None,Mon Jul 24 00:19:32 +0000 2017,"[0, 138]","{'hashtags': [{'text': 'BarkWeek', 'indices': ...","{'media': [{'id': 889278779352338437, 'id_str'...",25008,False,This is Oliver. You're witnessing one of his m...,None,...,en,None,False,False,5355,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1180,None,None,Mon Jul 24 17:02:04 +0000 2017,"[0, 118]","{'hashtags': [{'text': 'BarkWeek', 'indices': ...","{'media': [{'id': 889531127467266049, 'id_str'...",14918,False,This is Stuart. He's sporting his favorite fan...,None,...,en,None,False,False,2213,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1181,None,None,Tue Jul 25 00:10:02 +0000 2017,"[0, 91]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 889638825424826374, 'id_str'...",26858,False,This is Ted. He does his best. Sometimes that'...,None,...,en,None,False,False,4490,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1182,None,None,Tue Jul 25 01:55:32 +0000 2017,"[0, 106]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 889665366129029120, 'id_str'...",47579,False,Here's a puppo that seems to be on the fence a...,None,...,en,None,False,False,9945,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1183,None,None,Tue Jul 25 16:11:53 +0000 2017,"[0, 107]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 889880888800096258, 'id_str'...",27464,False,This is Bruno. He is a service shark. Only get...,None,...,en,None,False,False,4918,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1184,None,None,Wed Jul 26 00:31:25 +0000 2017,"[0, 130]","{'hashtags': [{'text': 'BarkWeek', 'indices': ...","{'media': [{'id': 890006600089468928, 'id_str'...",30312,False,This is Koda. He is a South Australian decksha...,None,...,en,None,False,False,7245,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1185,None,None,Wed Jul 26 15:59:51 +0000 2017,"[0, 133]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 890240245463175168, 'id_str'...",31553,False,This is Cassie. She is a college pup. Studying...,None,...,en,None,False,False,7300,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1186,None,None,Thu Jul 27 16:25:51 +0000 2017,"[0, 122]","{'hashtags': [{'text': 'BarkWeek', 'indices': ...","{'media': [{'id': 890609177319665665, 'id_str'...",27504,False,This is Zoey. She doesn't want to be one of th...,None,...,en,None,False,False,4217,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."

In [8]:
tweet_js.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1195 entries, 0 to 1194
Data columns (total 28 columns):
contributors                     0 non-null object
coordinates                      0 non-null object
created_at                       1195 non-null object
display_text_range               1195 non-null object
entities                         1195 non-null object
extended_entities                1195 non-null object
favorite_count                   1195 non-null int64
favorited                        1195 non-null bool
full_text                        1195 non-null object
geo                              0 non-null object
id                               1195 non-null int64
id_str                           1195 non-null object
in_reply_to_screen_name          16 non-null object
in_reply_to_status_id            16 non-null float64
in_reply_to_status_id_str        16 non-null object
in_reply_to_user_id              16 non-null float64
in_reply_to_user_id_str          16 non-null object
is_quote_status                  1195 non-null bool
lang                             1195 non-null object
place                            0 non-null object
possibly_sensitive               1195 non-null bool
possibly_sensitive_appealable    1195 non-null bool
retweet_count                    1195 non-null int64
retweeted                        1195 non-null bool
retweeted_status                 16 non-null object
source                           1195 non-null object
truncated                        1195 non-null bool
user                             1195 non-null object
dtypes: bool(6), float64(2), int64(3), object(17)
memory usage: 212.5+ KB

PRIMEIROS COMENTÁRIOS/PROBLEMAS:

    Somente as colunas "id","retweet_count","favorite_count" e "created at" são necessários
    
    A coluna "id" esta inteiro, sendo que deveria ser string
    
    A coluna "created at" pode ser modificada para mostrar somente a mês e o ano , em colunas separas em forma de string
    
    Existe 1195 objetos, porém nem todas as colunas estão completadas

VERIFICANDO AS COLUNAS DISCUTIDAS

In [15]:
tweet_js.id[:5]

0    666020888022790149
1    666029285002620928
2    666033412701032449
3    666044226329800704
4    666049248165822465
Name: id, dtype: int64

In [16]:
tweet_js.retweet_count[:5]

0    508
1     47
2     44
3    139
4     40
Name: retweet_count, dtype: int64

In [17]:
tweet_js.favorite_count[:5]

0    2551
1     128
2     125
3     296
4     108
Name: favorite_count, dtype: int64

In [22]:
tweet_js.created_at[:5]

0    Sun Nov 15 22:32:08 +0000 2015
1    Sun Nov 15 23:05:30 +0000 2015
2    Sun Nov 15 23:21:54 +0000 2015
3    Mon Nov 16 00:04:52 +0000 2015
4    Mon Nov 16 00:24:50 +0000 2015
Name: created_at, dtype: object

IMAGENS_PRE

In [25]:
imagens_pre.head()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

In [24]:
imagens_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
tweet_id    2075 non-null int64
jpg_url     2075 non-null object
img_num     2075 non-null int64
p1          2075 non-null object
p1_conf     2075 non-null float64
p1_dog      2075 non-null bool
p2          2075 non-null object
p2_conf     2075 non-null float64
p2_dog      2075 non-null bool
p3          2075 non-null object
p3_conf     2075 non-null float64
p3_dog      2075 non-null bool
dtypes: bool(3), float64(3), int64(2), object(4)
memory usage: 152.1+ KB

PRIMEIROS COMENTÁRIOS/PROBLEMAS:
    "tweet_id" deve ser string
    
    A coluna img_num não acrescenta informação
    
    As colunas px_conf indica qual é a probabilidade do cachorro ter a descendencia. p1 indica a maior probabilidade. Se px_dog forem todos falsos, então não é cachorro
    
    Iniciar todos os nomes das raças com letra Maiscula para melhor order
    
    Probabilidades menos que 0.25 serão descondirados e seus valores devem ser substituidos por None
    
    existem 2075 elementos, todas as colunas estão completadas

VERIFICANDO AS COLUNAS DISCUTIDAS

In [48]:
imagens_pre[(imagens_pre['p1_dog'] == False) & (imagens_pre['p2_dog'] == False) & (imagens_pre['p3_dog'] == False)].count()[0]

324

In [60]:
imagens_pre.p1[(imagens_pre['p1_dog'] == True) & (imagens_pre['p2_dog'] == True) & (imagens_pre['p3_dog'] == True)].unique()

array(['Welsh_springer_spaniel', 'redbone', 'German_shepherd',
       'Rhodesian_ridgeback', 'miniature_pinscher',
       'Bernese_mountain_dog', 'miniature_poodle', 'golden_retriever',
       'Gordon_setter', 'Walker_hound', 'pug', 'bloodhound', 'Lhasa',
       'English_setter', 'Italian_greyhound', 'Maltese_dog', 'malamute',
       'soft-coated_wheaten_terrier', 'Chihuahua',
       'black-and-tan_coonhound', 'toy_terrier', 'Blenheim_spaniel',
       'Pembroke', 'curly-coated_retriever', 'dalmatian', 'Ibizan_hound',
       'Border_collie', 'Labrador_retriever', 'miniature_schnauzer',
       'Chesapeake_Bay_retriever', 'West_Highland_white_terrier',
       'toy_poodle', 'giant_schnauzer', 'vizsla', 'Rottweiler',
       'Siberian_husky', 'papillon', 'Saint_Bernard', 'Tibetan_terrier',
       'beagle', 'Yorkshire_terrier', 'Pomeranian', 'kuvasz',
       'flat-coated_retriever', 'Norwegian_elkhound', 'chow',
       'standard_poodle', 'Staffordshire_bullterrier', 'basenji',
       'Lakeland_terrier', 'American_Staffordshire_terrier', 'Shih-Tzu',
       'French_bulldog', 'Pekinese', 'malinois', 'kelpie',
       'Brittany_spaniel', 'cocker_spaniel', 'basset',
       'Brabancon_griffon', 'Airedale', 'German_short-haired_pointer',
       'Irish_terrier', 'cairn', 'English_springer', 'whippet',
       'Sussex_spaniel', 'Dandie_Dinmont', 'Norwich_terrier', 'keeshond',
       'Old_English_sheepdog', 'Samoyed', 'Doberman', 'Shetland_sheepdog',
       'Great_Pyrenees', 'schipperke', 'bull_mastiff', 'collie',
       'Eskimo_dog', 'Cardigan', 'Greater_Swiss_Mountain_dog', 'borzoi',
       'Scottish_deerhound', 'standard_schnauzer', 'Boston_bull',
       'Japanese_spaniel', 'Norfolk_terrier', 'boxer', 'EntleBucher',
       'bluetick', 'Irish_setter', 'Leonberg', 'Weimaraner', 'Great_Dane',
       'Tibetan_mastiff', 'Scotch_terrier', 'Mexican_hairless',
       'groenendael', 'Australian_terrier', 'briard', 'Appenzeller',
       'Border_terrier', 'Newfoundland', 'Bedlington_terrier', 'Saluki',
       'silky_terrier', 'Afghan_hound', 'clumber',
       'wire-haired_fox_terrier', 'Irish_water_spaniel'], dtype=object)

In [ ]:
TWEET_ARC

In [64]:
twitter_arc.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None

In [63]:
twitter_arc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(4), int64(3), object(10)
memory usage: 313.0+ KB

In [7]:
twitter_arc.text[0]

"This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 https://t.co/MgUWQ76dJU"

In [16]:
twitter_arc[twitter_arc['rating_denominator'] != 10].count()[0]

23

In [110]:
twitter_arc.name

0        Phineas
1          Tilly
2         Archie
3          Darla
4       Franklin
5           None
6            Jax
7           None
8           Zoey
9         Cassie
10          Koda
11         Bruno
12          None
13           Ted
14        Stuart
15        Oliver
16           Jim
17          Zeke
18       Ralphus
19        Canela
20        Gerald
21       Jeffrey
22          such
23        Canela
24          None
25          None
26          Maya
27        Mingus
28         Derek
29        Roscoe
          ...
2326       quite
2327           a
2328        None
2329        None
2330        None
2331        None
2332        None
2333          an
2334           a
2335          an
2336        None
2337        None
2338        None
2339        None
2340        None
2341        None
2342        None
2343        None
2344        None
2345         the
2346         the
2347           a
2348           a
2349          an
2350           a
2351        None
2352           a
2353           a
2354           a
2355        None
Name: name, Length: 2356, dtype: object

In [ ]:
twitter_arc

PRIMEIROS COMENTÁRIOS/PROBLEMAS:
    Dentro da coluna text, tem o link de forma reduzida. 
    Dentro da coluna text, tem o denominador e o numerador
    Existem colunar com valores faltando
    tweet_id deve sre string
    As colunas doggo,flooofer,pupper,puppo podem ser retirada e formar uma uica coluna
    A coluna source começa com a tag
    De acordo com a fonte dos dados, todos os denominadores devem ser zeros
    A coluna name está incompleta e com nomes errados
    Existe 2356 elementos, porém algumas colunas não estão completadas

APONTANDO OS PROBLEMAS

QUALIDADE:
    TWEET_JS:
        Existem colunas que são desncessárias
        A coluna id é int
    IMAGENS_PRE:
        A coluna tweet_id é int
        Existem objetos que não são cachorros
        Existem objetos que não sabe a sua descedencia
        As raças não seguem um padrão de escrita
        
    TWEET_ARC:
        A coluna tweet_id é int
        Existem colunas que são desnecessárias
        A coluna rating_denominas não segue o padrão do site
        A coluna name mostra nomes errados
        A coluna text mostra informações que não deveria esta contida nela
        
ARRUMAÇÃO:
    TWEET_JS:
         A coluna created está escrita de uma forma não util
    TWEET_ARC:
        Existe colunas que apresentam as mesmas informações
    GERAL:
        Existe elementos que estão faltando em pelo menos um dos dataframe

RESOLUÇÃO - QUALIDADE:
    TWEET_JS:
        Manter somente as colunas "id","retweet_count","favorite_count" e verificar as duas ultimas são int
        Converter a coluna id para string
        Mundar o nome da coluna id para tweet_id
    IMAGENS_PRE:
        Converte a coluna tweet_id para string
        Remover os objetos que tenha pelo menos uma das colunas px_dog falso
    TWEET_ARC:
        Converter a coluna tweet_id para string
        Excluir as colunas in_reply_to_status_id,in_reply_to_user_id,retweeted_status e outras semelhantes
        Retirar o link da coluna text
        Verificar se o numerador fornecido pela a coluna text é igual a coluna rating_numerador
        Contabilizar somente os objetos que tenha a coluna rating_denominador = 10
        Transformar todos so valores da coluna name que começa com letra minuscula para None
        Retirar a avaliação da coluna text

RESOLUÇÃO - ARRUMAÇÃO:
        TWEET_JS:
            Criar duas colunas. A primeira sera para armazenar o mes e a segunda para armazenar o ano (o ano será string)
            Excluir a coluna create_at
         TWEET_ARC:
            Criar uma nova coluna que terá a informação se o cachorro é doogo,floofer,pupper,puppom
        GERAL:
            Comparar o tweet_id e id de todos os dataframe e armazenar somente os objetos que seu id esta presente em todos os dataframes analisados

LIMPANDO

In [122]:
tweet_js_clean = tweet_js.copy()
imagens_pre_clean = imagens_pre.copy()
twitter_arc_clean = twitter_arc.copy()

TWEET_JS - LIMPANDO

In [167]:
tweet_js_clean.columns.values

array(['contributors', 'coordinates', 'created_at', 'display_text_range',
       'entities', 'extended_entities', 'favorite_count', 'favorited',
       'full_text', 'geo', 'id', 'id_str', 'in_reply_to_screen_name',
       'in_reply_to_status_id', 'in_reply_to_status_id_str',
       'in_reply_to_user_id', 'in_reply_to_user_id_str',
       'is_quote_status', 'lang', 'place', 'possibly_sensitive',
       'possibly_sensitive_appealable', 'retweet_count', 'retweeted',
       'retweeted_status', 'source', 'truncated', 'user'], dtype=object)

In [168]:
tweet_js_clean = tweet_js_clean[['id','retweet_count','favorite_count','created_at']]

In [169]:
tweet_js_clean['tweet_id'] = tweet_js_clean.id.astype(str)

In [170]:
tweet_js_clean.drop(['id'],axis=1,inplace=True)

In [171]:
Colu_mes = tweet_js_clean.created_at.values
Mes = []
Ano = []
for i in Colu_mes:
    Mes.append(i.split()[1])
    Ano.append(i.split()[5])

In [174]:
tweet_js_clean['Month_start'] = pd.Series(Mes)
tweet_js_clean['Year_start'] = pd.Series(Ano)
tweet_js_clean.drop(['created_at'],axis=1,inplace=True)

In [ ]:
TWEET_JS - VERIFICANDO MUDANÇAS

In [175]:
tweet_js_clean.head()

   retweet_count  favorite_count            tweet_id Month_start Year_start
0            508            2551  666020888022790149         Nov       2015
1             47             128  666029285002620928         Nov       2015
2             44             125  666033412701032449         Nov       2015
3            139             296  666044226329800704         Nov       2015
4             40             108  666049248165822465         Nov       2015

In [176]:
tweet_js_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1195 entries, 0 to 1194
Data columns (total 5 columns):
retweet_count     1195 non-null int64
favorite_count    1195 non-null int64
tweet_id          1195 non-null object
Month_start       1195 non-null object
Year_start        1195 non-null object
dtypes: int64(2), object(3)
memory usage: 46.8+ KB

IMAGENS_PRE - LIMPANDO

In [178]:
imagens_pre_clean.drop(columns=("img_num"),inplace=True)

In [179]:
N_cachorro = imagens_pre_clean[(imagens_pre_clean['p1_dog'] == False) | (imagens_pre_clean['p2_dog'] == False) | (imagens_pre_clean['p3_dog'] == False)]

In [180]:
Chances_baixas = imagens_pre_clean[(imagens_pre_clean['p1_conf'] < 0.2) & (imagens_pre_clean['p2_conf'] < 0.2) & (imagens_pre_clean['p3_conf'] < 0.2 )]

In [181]:
INDEX_N_CACHORRO = N_cachorro.index
INDEX_CHANCE_BAIXAS = Chances_baixas.index
INDEX = INDEX_N_CACHORRO.append(INDEX_CHANCE_BAIXAS)

In [182]:
imagens_pre_clean.drop(INDEX,inplace=True)

In [183]:
imagens_pre_clean['tweet_id'] = imagens_pre_clean['tweet_id'].astype(str)

In [185]:
imagens_pre_clean['p1'] = imagens_pre_clean.p1.str.upper()

In [186]:
imagens_pre_clean['p2'] = imagens_pre_clean.p2.str.upper()

In [187]:
imagens_pre_clean['p3'] = imagens_pre_clean.p3.str.upper()

In [193]:
imagens_pre_clean.drop(['p1_dog','p2_dog','p3_dog'],axis=1,inplace=True)

IMAGENS_PRE - VERIFICANDO MUDANÇAS

In [196]:
imagens_pre_clean.head()

,tweet_id,jpg_url,p1,p1_conf,p2,p2_conf,p3,p3_conf
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,WELSH_SPRINGER_SPANIEL,0.465074,COLLIE,0.156665,SHETLAND_SHEEPDOG,0.061428
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,REDBONE,0.506826,MINIATURE_PINSCHER,0.074192,RHODESIAN_RIDGEBACK,0.072010
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,GERMAN_SHEPHERD,0.596461,MALINOIS,0.138584,BLOODHOUND,0.116197
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,RHODESIAN_RIDGEBACK,0.408143,REDBONE,0.360687,MINIATURE_PINSCHER,0.222752
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,MINIATURE_PINSCHER,0.560311,ROTTWEILER,0.243682,DOBERMAN,0.154629

In [ ]:
 TWEET_ARC - LIMPANDO

In [116]:
twitter_arc_clean['tweet_id '] = twitter_arc_clean.tweet_id.astype(str)

Remover twwet que são retweet ou responsata

In [101]:
twitter_arc_clean["in_reply_to_status_id"] = twitter_arc_clean["in_reply_to_status_id"].astype(str)
twitter_arc_clean["retweeted_status_id"] = twitter_arc_clean["retweeted_status_id"].astype(str)

In [102]:
Replies = twitter_arc_clean[twitter_arc_clean["in_reply_to_status_id"] != "nan"]
retw = twitter_arc_clean[twitter_arc_clean["retweeted_status_id"] != "nan"]

In [103]:
twitter_arc_clean.drop(Replies["tweet_id"].index,inplace=True)
twitter_arc_clean.drop(retw["tweet_id"].index,inplace=True)

In [104]:
Name = twitter_arc_clean["text"].str.contains("This is ([A-Z][a-z])+")

/home/guilherme/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """Entry point for launching an IPython kernel.

In [105]:
twitter_arc_clean = twitter_arc_clean[Name]

In [106]:
twitter_arc_clean["name"] = twitter_arc_clean.text.str.extract("This is ([A-Z][a-z]+).", expand=False)

In [125]:
twitter_arc_clean.text[0]

"This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 https://t.co/MgUWQ76dJU"

In [128]:
twitter_arc_clean.columns

Index(['tweet_id', 'in_reply_to_status_id', 'in_reply_to_user_id', 'timestamp',
       'source', 'text', 'retweeted_status_id', 'retweeted_status_user_id',
       'retweeted_status_timestamp', 'expanded_urls', 'rating_numerator',
       'rating_denominator', 'name', 'doggo', 'floofer', 'pupper', 'puppo'],
      dtype='object')

twitter_arc_clean.text.str.contains('|'.join(["doggo","pupper","floofer","puppo"]))

In [130]:
twitter_arc_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(4), int64(3), object(10)
memory usage: 313.0+ KB

In [131]:
state_doggo = twitter_arc_clean[twitter_arc_clean["doggo"] != "None" ]["tweet_id"].index

In [132]:
Dog_state = []
for i in range(le
    if i in state_doggo

Int64Index([   9,   43,   99,  108,  110,  121,  172,  191,  200,  211,  240,
             248,  300,  318,  323,  331,  339,  344,  345,  351,  359,  362,
             363,  372,  384,  385,  389,  391,  423,  425,  426,  429,  440,
             446,  447,  448,  449,  460,  489,  493,  499,  501,  531,  565,
             574,  575,  576,  585,  587,  616,  624,  698,  705,  724,  727,
             731,  733,  746,  764,  778,  780,  782,  807,  818,  822,  835,
             839,  857,  877,  881,  889,  899,  914,  919,  924,  944,  945,
             948,  956,  967,  977,  985,  989,  992, 1030, 1039, 1051, 1063,
            1075, 1079, 1103, 1113, 1117, 1141, 1156, 1176, 1204],
           dtype='int64')

In [ ]:
Remover colunas desnecessarias

In [120]:
Remover_col = ["timestamp","expanded_urls", "doggo", "floofer", "pupper", "puppo",
                   "in_reply_to_status_id", "in_reply_to_user_id", 
                   "retweeted_status_id", "retweeted_status_user_id", 
                    "retweeted_status_timestamp"]
twitter_arc_clean.drop(columns=Remover_col,inplace=True)

ValueError: labels ['expanded_urls' 'doggo' 'floofer' 'pupper' 'puppo'
 'in_reply_to_status_id' 'in_reply_to_user_id' 'retweeted_status_id'
 'retweeted_status_user_id' 'retweeted_status_timestamp'] not contained in axis

In [108]:
len_html = len(twitter_arc_clean["text"][0].split()[-1])+1
twitter_arc_clean["text"] = twitter_arc_clean["text"].apply(lambda x: x[:-len_html])

In [109]:
twitter_arc_clean["text"]

0       This is Phineas. He's a mystical boy. Only eve...
1       This is Tilly. She's just checking pup on you....
2       This is Archie. He is a rare Norwegian Pouncin...
3       This is Darla. She commenced a snooze mid meal...
4       This is Franklin. He would like you to stop ca...
8       This is Zoey. She doesn't want to be one of th...
9       This is Cassie. She is a college pup. Studying...
10      This is Koda. He is a South Australian decksha...
11      This is Bruno. He is a service shark. Only get...
13      This is Ted. He does his best. Sometimes that'...
14      This is Stuart. He's sporting his favorite fan...
15      This is Oliver. You're witnessing one of his m...
16      This is Jim. He found a fren. Taught him how t...
17      This is Zeke. He has a new stick. Very proud o...
18      This is Ralphus. He's powering up. Attempting ...
20      This is Gerald. He was just told he didn't get...
21      This is Jeffrey. He has a monopoly on the pool...
23      This is Canela. She attempted some fancy porch...
26      This is Maya. She's very shy. Rarely leaves he...
27      This is Mingus. He's a wonderful father to his...
28      This is Derek. He's late for a dog meeting. 13...
29      This is Roscoe. Another pupper fallen victim t...
31      This is Waffles. His doggles are pupside down....
33      Viewer discretion advised. This is Jimbo. He w...
34      This is Maisey. She fell asleep mid-excavation...
38      This is Earl. He found a hat. Nervous about wh...
39      This is Lola. It's her first time outside. Mus...
40      This is Kevin. He's just so happy. 13/10 what ...
44      This is Noah. He can't believe someone made th...
45      This is Bella. She hopes her smile made you sm...
                              ...
2251    This is Filup. He is overcome with joy after f...
2256    This is Calvin. He is a Luxembourgian Mayo. Ha...
2263    This is Kial. Kial is either wearing a cape, w...
2265    This is Frank (pronounced "Fronq"). Too many b...
2268    This is Dook &amp; Milo. Dook is struggling to...
2271    This is Philippe from Soviet Russia. Commandin...
2274    This is Reese and Twips. Reese protects Twips....
2279            This is Biden. Biden just tripped... 7/10
2280    This is Fwed. He is a Canadian Asian Taylormad...
2282    This is Genevieve. She is a golden retriever c...
2283    This is Joshwa. He is a fuckboy supreme. He cl...
2286    This is Timison. He just told an awful joke bu...
2289    This is Clarence. His face says he doesn't wan...
2291    This is Churlie. AKA Fetty Woof. Lost eye savi...
2292    This is Bradlay. He is a Ronaldinho Matsuyama ...
2293    This is Pipsy. He is a fluffball. Enjoys trave...
2295    This is Gabe. He is a southern Baklava. Gabe h...
2296    This is Clybe. He is an Anemone Valdez. One ea...
2300    This is Keet. He is a Floridian Amukamara. Abs...
2302    This is Klevin. He laughs a lot. Very cool dog...
2303    This is Carll. He wants to be a donkey. But al...
2308    This is Jeph. He is a German Boston Shuttlecoc...
2309    This is Jockson. He is a Pinnacle Sagittarius....
2312    This is Josep. He is a Rye Manganese mix. Can ...
2313    This is Lugan. He is a Bohemian Rhapsody. Very...
2315    This is Christoper. He is a spotted Penne. Can...
2317    This is Jimothy. He is a Botwanian Gouda. Can ...
2318    I'll name the dogs from now on. This is Kreggo...
2319    This is Scout. She is a black Downton Abbey. I...
2325    This is Walter. He is an Alaskan Terrapin. Lov...
Name: text, Length: 1075, dtype: object

In [110]:
Denominador_correto = twitter_arc_clean.text.str.contains("\d+/10")

In [111]:
twitter_arc_clean = twitter_arc_clean[Denominador_correto]

In [86]:
twitter_arc_clean

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None
5,891087950875897856,NaN,NaN,2017-07-29 00:08:17 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a majestic great white breaching ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891087950...,13,10,None,None,None,None,None
6,890971913173991426,NaN,NaN,2017-07-28 16:27:12 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Meet Jax. He enjoys ice cream so much he gets ...,NaN,NaN,NaN,"https://gofundme.com/ydvmve-surgery-for-jax,ht...",13,10,Jax,None,None,None,None
7,890729181411237888,NaN,NaN,2017-07-28 00:22:40 +0000,"<a href=""http://twitter.com/download/iphone"" r...",When you watch your owner call another dog a g...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890729181...,13,10,None,None,None,None,None
8,890609185150312448,NaN,NaN,2017-07-27 16:25:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Zoey. She doesn't want to be one of th...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890609185...,13,10,Zoey,None,None,None,None
9,890240255349198849,NaN,NaN,2017-07-26 15:59:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Cassie. She is a college pup. Studying...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890240255...,14,10,Cassie,doggo,None,None,None
10,890006608113172480,NaN,NaN,2017-07-26 00:31:25 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Koda. He is a South Australian decksha...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890006608...,13,10,Koda,None,None,None,None
11,889880896479866881,NaN,NaN,2017-07-25 16:11:53 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Bruno. He is a service shark. Only get...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889880896...,13,10,Bruno,None,None,None,None
12,889665388333682689,NaN,NaN,2017-07-25 01:55:32 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here's a puppo that seems to be on the fence a...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889665388...,13,10,None,None,None,None,puppo
13,889638837579907072,NaN,NaN,2017-07-25 00:10:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Ted. He does his best. Sometimes that'...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889638837...,12,10,Ted,None,None,None,None
14,889531135344209921,NaN,NaN,2017-07-24 17:02:04 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Stuart. He's sporting his favorite fan...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889531135...,13,10,Stuart,None,None,None,puppo
15,889278841981685760,NaN,NaN,2017-07-24 00:19:32 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Oliver. You're witnessing one of his m...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889278841...,13,10,Oliver,None,None,None,None
16,888917238123831296,NaN,NaN,2017-07-23 00:22:39 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Jim. He found a fren. Taught him how t...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888917238...,12,10,Jim,None,None,None,None
17,888804989199671297,NaN,NaN,2017-07-22 16:56:37 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Zeke. He has a new stick. Very proud o...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888804989...,13,10,Zeke,None,None,None,None
18,888554962724278272,NaN,NaN,2017-07-22 00:23:06 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Ralphus. He's powering up. Attempting ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888554962...,13,10,Ralphus,None,None,None,None
19,888202515573088257,NaN,NaN,2017-07-21 01:02:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",RT @dog_rates: This is Canela. She attempted s...,8.874740e+17,4.196984e+09,2017-07-19 00:47:34 +0000,https://twitter.com/dog_rates/status/887473957...,13,10,Canela,None,None,None,None
20,888078434458587136,NaN,NaN,2017-07-20 16:49:33 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Gerald. He was just told he didn't get...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888078434...,12,10,Gerald,None,None,None,None
21,887705289381826560,NaN,NaN,2017-07-19 16:06:48 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Jeffrey. He has a monopoly on the pool...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887705289...,13,10,Jeffrey,None,None,None,None
22,887517139158093824,NaN,NaN,2017-07-19 03:39:09 +0000,"<a href=""http://twitter.com/download/iphone"" r...",I've yet to rate a Venezuelan Hover Wiener. Th...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887517139...,14,10,such,None,None,None,None
23,887473957103951883,NaN,NaN,2017-07-19 00:47:34 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Canela. She attempted some fancy porch...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887473957...,13,10,Canela,None,None,None,None
24,887343217045368832,NaN,NaN,2017-07-18 16:08:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",You may not have known you needed to see this ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887343217...,13,10,None,None,None,None,None
25,887101392804085760,NaN,NaN,2017-07-18 00:07:08 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This... is a Jubilant Antarctic House Bear. We...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887101392...,12,10,None,None,None,None,None
26,886983233522544640,NaN,NaN,2017-07-17 16:17:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Maya. She's very shy. Rarely leaves he...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/886983233...,13,10,Maya,None,None,None,None
27,886736880519319552,NaN,NaN,2017-07-16 23:58:41 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Mingus. He's a wonderful father to his...,NaN,NaN,NaN,"https://www.gofundme.com/mingusneedsus,https:/...",13,10,Mingus,None,None,None,None
28,886680336477933568,NaN,NaN,2017-07-16 20:14:00 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Derek. He's late for a dog meeting. 13...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/886680336...,13,10,Derek,None,None,None,None
29,886366144734445568,NaN,NaN,2017-07-15 23:25:31 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Roscoe. Another pupper fallen victim t...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/886366144...,12,10,Roscoe,None,None,pupper,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326,666411507551481857,NaN,NaN,2015-11-17 00:24:19 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is quite the dog. Gets really excited whe...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666411507...,2,10,quite,None,None,None,None
2327,666407126856765440,NaN,NaN,2015-11-17 00:06:54 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a southern Vesuvius bumblegruff. Can d...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666407126...,7,10,a,None,None,None,None
2328,666396247373291520,NaN,NaN,2015-11-16 23:23:41 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Oh goodness. A super rare northeast Qdoba kang...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666396247...,9,10,None,None,None,None,None
2329,666373753744588802,NaN,NaN,2015-11-16 21:54:18 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Those are sunglasses and a jean jacket. 11/10 ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666373753...,11,10,None,None,None,None,None
2330,666362758909284353,NaN,NaN,2015-11-16 21:10:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Unique dog here. Very small. Lives in containe...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666362758...,6,10,None,None,None,None,None
2331,666353288456101888,NaN,NaN,2015-11-16 20:32:58 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a mixed Asiago from the Galápagos...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666353288...,8,10,None,None,None,None,None
2332,666345417576210432,NaN,NaN,2015-11-16 20:01:42 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Look at this jokester thinking seat belt laws ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666345417...,10,10,None,None,None,None,None
2333,666337882303524864,NaN,NaN,2015-11-16 19:31:45 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an extremely rare horned Parthenon. No...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666337882...,9,10,an,None,None,None,None
2334,666293911632134144,NaN,NaN,2015-11-16 16:37:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a funny dog. Weird toes. Won't come do...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666293911...,3,10,a,None,None,None,None
2335,666287406224695296,NaN,NaN,2015-11-16 16:11:11 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an Albanian 3 1/2 legged Episcopalian...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666287406...,1,2,an,None,None,None,None
2336,666273097616637952,NaN,NaN,2015-11-16 15:14:19 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Can take selfies 11/10 https://t.co/ws2AMaNwPW,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666273097...,11,10,None,None,None,None,None
2337,666268910803644416,NaN,NaN,2015-11-16 14:57:41 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Very concerned about fellow dog trapped in com...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666268910...,10,10,None,None,None,None,None
2338,666104133288665088,NaN,NaN,2015-11-16 04:02:55 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Not familiar with this breed. No tail (weird)....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666104133...,1,10,None,None,None,None,None
2339,666102155909144576,NaN,NaN,2015-11-16 03:55:04 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Oh my. Here you are seeing an Adobe Setter giv...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666102155...,11,10,None,None,None,None,None
2340,666099513787052032,NaN,NaN,2015-11-16 03:44:34 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Can stand on stump for what seems like a while...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666099513...,8,10,None,None,None,None,None
2341,666094000022159362,NaN,NaN,2015-11-16 03:22:39 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This appears to be a Mongolian Presbyterian mi...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666094000...,9,10,None,None,None,None,None
2342,666082916733198337,NaN,NaN,2015-11-16 02:38:37 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a well-established sunblockerspan...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666082916...,6,10,None,None,None,None,None
2343,666073100786774016,NaN,NaN,2015-11-16 01:59:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Let's hope this flight isn't Malaysian (lol). ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666073100...,10,10,None,None,None,None,None
2344,666071193221509120,NaN,NaN,2015-11-16 01:52:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a northern speckled Rhododendron....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666071193...,9,10,None,None,None,None,None
2345,666063827256086533,NaN,NaN,2015-11-16 01:22:45 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is the happiest dog you will ever see. Ve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666063827...,10,10,the,None,None,None,None
2346,666058600524156928,NaN,NaN,2015-11-16 01:01:59 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is the Rand Paul of retrievers folks! He'...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666058600...,8,10,the,None,None,None,None
2347,666057090499244032,NaN,NaN,2015-11-16 00:55:59 +0000,"<a href=""http://twitter.com/download/iphone"" r...",My oh my. This is a rare blond Canadian terrie...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666057090...,9,10,a,None,None,None,None
2348,666055525042405380,NaN,NaN,2015-11-16 00:49:46 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a Siberian heavily armored polar bear ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666055525...,10,10,a,None,None,None,None
2349,666051853826850816,NaN,NaN,2015-11-16 00:35:11 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an odd dog. Hard on the outside but lo...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666051853...,2,10,an,None,None,None,None
2350,666050758794694657,NaN,NaN,2015-11-16 00:30:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a truly beautiful English Wilson Staff...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666050758...,10,10,a,None,None,None,None
2351,666049248165822465,NaN,NaN,2015-11-16 00:24:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a 1949 1st generation vulpix. Enj...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666049248...,5,10,None,None,None,None,None
2352,666044226329800704,NaN,NaN,2015-11-16 00:04:52 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a purebred Piers Morgan. Loves to Netf...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666044226...,6,10,a,None,None,None,None
2353,666033412701032449,NaN,NaN,2015-11-15 23:21:54 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a very happy pup. Big fan of well-main...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666033412...,9,10,a,None,None,None,None
2354,666029285002620928,NaN,NaN,2015-11-15 23:05:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a western brown Mitsubishi terrier. Up...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666029285...,7,10,a,None,None,None,None
2355,666020888022790149,NaN,NaN,2015-11-15 22:32:08 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a Japanese Irish Setter. Lost eye...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666020888...,8,10,None,None,None,None,None

In [112]:
source = twitter_arc_clean.source.values

In [113]:
for i in range(len(source)):
    source[i] = source[i].split('"')[1]

In [114]:
twitter_arc_clean

,tweet_id,timestamp,source,text,rating_numerator,rating_denominator,name,tweet_id
0,892420643555336193,2017-08-01 16:23:56 +0000,http://twitter.com/download/iphone,This is Phineas. He's a mystical boy. Only eve...,13,10,Phineas,892420643555336193
1,892177421306343426,2017-08-01 00:17:27 +0000,http://twitter.com/download/iphone,This is Tilly. She's just checking pup on you....,13,10,Tilly,892177421306343426
2,891815181378084864,2017-07-31 00:18:03 +0000,http://twitter.com/download/iphone,This is Archie. He is a rare Norwegian Pouncin...,12,10,Archie,891815181378084864
3,891689557279858688,2017-07-30 15:58:51 +0000,http://twitter.com/download/iphone,This is Darla. She commenced a snooze mid meal...,13,10,Darla,891689557279858688
4,891327558926688256,2017-07-29 16:00:24 +0000,http://twitter.com/download/iphone,This is Franklin. He would like you to stop ca...,12,10,Franklin,891327558926688256
8,890609185150312448,2017-07-27 16:25:51 +0000,http://twitter.com/download/iphone,This is Zoey. She doesn't want to be one of th...,13,10,Zoey,890609185150312448
9,890240255349198849,2017-07-26 15:59:51 +0000,http://twitter.com/download/iphone,This is Cassie. She is a college pup. Studying...,14,10,Cassie,890240255349198849
10,890006608113172480,2017-07-26 00:31:25 +0000,http://twitter.com/download/iphone,This is Koda. He is a South Australian decksha...,13,10,Koda,890006608113172480
11,889880896479866881,2017-07-25 16:11:53 +0000,http://twitter.com/download/iphone,This is Bruno. He is a service shark. Only get...,13,10,Bruno,889880896479866881
13,889638837579907072,2017-07-25 00:10:02 +0000,http://twitter.com/download/iphone,This is Ted. He does his best. Sometimes that'...,12,10,Ted,889638837579907072
14,889531135344209921,2017-07-24 17:02:04 +0000,http://twitter.com/download/iphone,This is Stuart. He's sporting his favorite fan...,13,10,Stuart,889531135344209921
15,889278841981685760,2017-07-24 00:19:32 +0000,http://twitter.com/download/iphone,This is Oliver. You're witnessing one of his m...,13,10,Oliver,889278841981685760
16,888917238123831296,2017-07-23 00:22:39 +0000,http://twitter.com/download/iphone,This is Jim. He found a fren. Taught him how t...,12,10,Jim,888917238123831296
17,888804989199671297,2017-07-22 16:56:37 +0000,http://twitter.com/download/iphone,This is Zeke. He has a new stick. Very proud o...,13,10,Zeke,888804989199671297
18,888554962724278272,2017-07-22 00:23:06 +0000,http://twitter.com/download/iphone,This is Ralphus. He's powering up. Attempting ...,13,10,Ralphus,888554962724278272
20,888078434458587136,2017-07-20 16:49:33 +0000,http://twitter.com/download/iphone,This is Gerald. He was just told he didn't get...,12,10,Gerald,888078434458587136
21,887705289381826560,2017-07-19 16:06:48 +0000,http://twitter.com/download/iphone,This is Jeffrey. He has a monopoly on the pool...,13,10,Jeffrey,887705289381826560
23,887473957103951883,2017-07-19 00:47:34 +0000,http://twitter.com/download/iphone,This is Canela. She attempted some fancy porch...,13,10,Canela,887473957103951883
26,886983233522544640,2017-07-17 16:17:36 +0000,http://twitter.com/download/iphone,This is Maya. She's very shy. Rarely leaves he...,13,10,Maya,886983233522544640
27,886736880519319552,2017-07-16 23:58:41 +0000,http://twitter.com/download/iphone,This is Mingus. He's a wonderful father to his...,13,10,Mingus,886736880519319552
28,886680336477933568,2017-07-16 20:14:00 +0000,http://twitter.com/download/iphone,This is Derek. He's late for a dog meeting. 13...,13,10,Derek,886680336477933568
29,886366144734445568,2017-07-15 23:25:31 +0000,http://twitter.com/download/iphone,This is Roscoe. Another pupper fallen victim t...,12,10,Roscoe,886366144734445568
31,886258384151887873,2017-07-15 16:17:19 +0000,http://twitter.com/download/iphone,This is Waffles. His doggles are pupside down....,13,10,Waffles,886258384151887873
33,885984800019947520,2017-07-14 22:10:11 +0000,http://twitter.com/download/iphone,Viewer discretion advised. This is Jimbo. He w...,12,10,Jimbo,885984800019947520
34,885528943205470208,2017-07-13 15:58:47 +0000,http://twitter.com/download/iphone,This is Maisey. She fell asleep mid-excavation...,13,10,Maisey,885528943205470208
38,884925521741709313,2017-07-12 00:01:00 +0000,http://twitter.com/download/iphone,This is Earl. He found a hat. Nervous about wh...,12,10,Earl,884925521741709313
39,884876753390489601,2017-07-11 20:47:12 +0000,http://twitter.com/download/iphone,This is Lola. It's her first time outside. Mus...,13,10,Lola,884876753390489601
40,884562892145688576,2017-07-11 00:00:02 +0000,http://twitter.com/download/iphone,This is Kevin. He's just so happy. 13/10 what ...,13,10,Kevin,884562892145688576
44,883838122936631299,2017-07-09 00:00:04 +0000,http://twitter.com/download/iphone,This is Noah. He can't believe someone made th...,12,10,Noah,883838122936631299
45,883482846933004288,2017-07-08 00:28:19 +0000,http://twitter.com/download/iphone,This is Bella. She hopes her smile made you sm...,5,10,Bella,883482846933004288
...,...,...,...,...,...,...,...,...
2251,667806454573760512,2015-11-20 20:47:20 +0000,http://twitter.com/download/iphone,This is Filup. He is overcome with joy after f...,10,10,Filup,667806454573760512
2256,667766675769573376,2015-11-20 18:09:16 +0000,http://twitter.com,This is Calvin. He is a Luxembourgian Mayo. Ha...,9,10,Calvin,667766675769573376
2263,667544320556335104,2015-11-20 03:25:43 +0000,http://twitter.com,"This is Kial. Kial is either wearing a cape, w...",10,10,Kial,667544320556335104
2265,667534815156183040,2015-11-20 02:47:56 +0000,http://twitter.com,"This is Frank (pronounced ""Fronq""). Too many b...",8,10,Frank,667534815156183040
2268,667517642048163840,2015-11-20 01:39:42 +0000,http://twitter.com,This is Dook &amp; Milo. Dook is struggling to...,8,10,Dook,667517642048163840
2271,667495797102141441,2015-11-20 00:12:54 +0000,http://twitter.com,This is Philippe from Soviet Russia. Commandin...,9,10,Philippe,667495797102141441
2274,667455448082227200,2015-11-19 21:32:34 +0000,http://twitter.com,This is Reese and Twips. Reese protects Twips....,7,10,Reese,667455448082227200
2279,667405339315146752,2015-11-19 18:13:27 +0000,http://twitter.com/download/iphone,This is Biden. Biden just tripped... 7/10,7,10,Biden,667405339315146752
2280,667393430834667520,2015-11-19 17:26:08 +0000,http://twitter.com/download/iphone,This is Fwed. He is a Canadian Asian Taylormad...,8,10,Fwed,667393430834667520
2282,667211855547486208,2015-11-19 05:24:37 +0000,http://twitter.com/download/iphone,This is Genevieve. She is a golden retriever c...,9,10,Genevieve,667211855547486208
2283,667200525029539841,2015-11-19 04:39:35 +0000,http://twitter.com/download/iphone,This is Joshwa. He is a fuckboy supreme. He cl...,11,10,Joshwa,667200525029539841
2286,667182792070062081,2015-11-19 03:29:07 +0000,http://twitter.com/download/iphone,This is Timison. He just told an awful joke bu...,10,10,Timison,667182792070062081
2289,667174963120574464,2015-11-19 02:58:01 +0000,http://twitter.com/download/iphone,This is Clarence. His face says he doesn't wan...,9,10,Clarence,667174963120574464
2291,667165590075940865,2015-11-19 02:20:46 +0000,http://twitter.com/download/iphone,This is Churlie. AKA Fetty Woof. Lost eye savi...,10,10,Churlie,667165590075940865
2292,667160273090932737,2015-11-19 01:59:39 +0000,http://twitter.com/download/iphone,This is Bradlay. He is a Ronaldinho Matsuyama ...,11,10,Bradlay,667160273090932737
2293,667152164079423490,2015-11-19 01:27:25 +0000,http://twitter.com/download/iphone,This is Pipsy. He is a fluffball. Enjoys trave...,12,10,Pipsy,667152164079423490
2295,667119796878725120,2015-11-18 23:18:48 +0000,http://twitter.com/download/iphone,This is Gabe. He is a southern Baklava. Gabe h...,10,10,Gabe,667119796878725120
2296,667090893657276420,2015-11-18 21:23:57 +0000,http://twitter.com/download/iphone,This is Clybe. He is an Anemone Valdez. One ea...,7,10,Clybe,667090893657276420
2300,667062181243039745,2015-11-18 19:29:52 +0000,http://twitter.com/download/iphone,This is Keet. He is a Floridian Amukamara. Abs...,10,10,Keet,667062181243039745
2302,667012601033924608,2015-11-18 16:12:51 +0000,http://twitter.com/download/iphone,This is Klevin. He laughs a lot. Very cool dog...,9,10,Klevin,667012601033924608
2303,666996132027977728,2015-11-18 15:07:24 +0000,http://twitter.com/download/iphone,This is Carll. He wants to be a donkey. But al...,10,10,Carll,666996132027977728
2308,666817836334096384,2015-11-18 03:18:55 +0000,http://twitter.com/download/iphone,This is Jeph. He is a German Boston Shuttlecoc...,9,10,Jeph,666817836334096384
2309,666804364988780544,2015-11-18 02:25:23 +0000,http://twitter.com/download/iphone,This is Jockson. He is a Pinnacle Sagittarius....,8,10,Jockson,666804364988780544
2312,666776908487630848,2015-11-18 00:36:17 +0000,http://twitter.com/download/iphone,This is Josep. He is a Rye Manganese mix. Can ...,5,10,Josep,666776908487630848
2313,666739327293083650,2015-11-17 22:06:57 +0000,http://twitter.com/download/iphone,This is Lugan. He is a Bohemian Rhapsody. Very...,10,10,Lugan,666739327293083650
2315,666691418707132416,2015-11-17 18:56:35 +0000,http://twitter.com/download/iphone,This is Christoper. He is a spotted Penne. Can...,8,10,Christoper,666691418707132416
2317,666644823164719104,2015-11-17 15:51:26 +0000,http://twitter.com/download/iphone,This is Jimothy. He is a Botwanian Gouda. Can ...,9,10,Jimothy,666644823164719104
2318,666454714377183233,2015-11-17 03:16:00 +0000,http://twitter.com/download/iphone,I'll name the dogs from now on. This is Kreggo...,10,10,Kreggory,666454714377183233
2319,666447344410484738,2015-11-17 02:46:43 +0000,http://twitter.com/download/iphone,This is Scout. She is a black Downton Abbey. I...,9,10,Scout,666447344410484738
2325,666418789513326592,2015-11-17 00:53:15 +0000,http://twitter.com/download/iphone,This is Walter. He is an Alaskan Terrapin. Lov...,10,10,Walter,666418789513326592

In [118]:
twitter_arc_clean["tweet_id"] = twitter_arc_clean.tweet_id.astype(str)

In [119]:
twitter_arc_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1075 entries, 0 to 2325
Data columns (total 8 columns):
tweet_id              1075 non-null object
timestamp             1075 non-null object
source                1075 non-null object
text                  1075 non-null object
rating_numerator      1075 non-null int64
rating_denominator    1075 non-null int64
name                  1075 non-null object
tweet_id              1075 non-null object
dtypes: int64(2), object(6)
memory usage: 75.6+ KB